version: '3.8'

services:
  db:
    container_name: pg-student
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
